version: '2'
services:
    todojhipster-app:
        image: todojhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://todojhipster-postgresql:5432/ToDoJHipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    todojhipster-postgresql:
        extends:
            file: postgresql.yml
            service: todojhipster-postgresql
